import { useEffect, useState } from 'react';
import { Building2, CalendarRange, RefreshCw, TrendingUp, WalletCards } from 'lucide-react';
import { api } from '../api';
import { useScope } from '../store';

type Row={clientId:string;name:string;spend:number;leads:number;conversations:number;purchases:number;revenue:number;ctr:number;cpc:number;cpm:number;costPerLead:number;costPerConversation:number;costPerPurchase:number;roas:number;bmCount:number;accountCount:number;error?:string};
const today=()=>new Date().toISOString().slice(0,10);const ago=(d:number)=>{const x=new Date();x.setDate(x.getDate()-d);return x.toISOString().slice(0,10)};const n=(v:any)=>Number(v||0);const money=(v:any)=>n(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});const integer=(v:any)=>Math.round(n(v)).toLocaleString('pt-BR');const dec=(v:any)=>n(v).toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2});
export default function AgencyOverview(){const scope=useScope();const[since,setSince]=useState(ago(29));const[until,setUntil]=useState(today());const[rows,setRows]=useState<Row[]>([]);const[loading,setLoading]=useState(false);const[error,setError]=useState('');
 async function load(){setLoading(true);setError('');try{const ctx=await api.get('/workspace/context');const clients=Array.isArray(ctx.data?.data?.clients)?ctx.data.data.clients:[];const businesses=Array.isArray(ctx.data?.data?.businesses)?ctx.data.data.businesses:[];const accounts=Array.isArray(ctx.data?.data?.accounts)?ctx.data.data.accounts:[];const results:Row[]=[];for(const client of clients){try{const r=await api.get('/performance/summary',{params:{clientId:client.id,since,until}});const m=r.data?.data||{};results.push({clientId:client.id,name:client.name,spend:n(m.spend),leads:n(m.leads),conversations:n(m.conversations),purchases:n(m.purchases),revenue:n(m.revenue),ctr:n(m.ctr),cpc:n(m.cpc),cpm:n(m.cpm),costPerLead:n(m.costPerLead),costPerConversation:n(m.costPerConversation),costPerPurchase:n(m.costPerPurchase),roas:n(m.roas),bmCount:businesses.filter((b:any)=>b.clientId===client.id).length,accountCount:accounts.filter((a:any)=>a.clientId===client.id&&a.isAssigned).length});}catch{results.push({clientId:client.id,name:client.name,spend:0,leads:0,conversations:0,purchases:0,revenue:0,ctr:0,cpc:0,cpm:0,costPerLead:0,costPerConversation:0,costPerPurchase:0,roas:0,bmCount:businesses.filter((b:any)=>b.clientId===client.id).length,accountCount:accounts.filter((a:any)=>a.clientId===client.id&&a.isAssigned).length,error:'Dados indisponíveis'});}}setRows(results);}catch(e:any){setError(e?.response?.data?.error?.message||'Não foi possível carregar a visão da agência.');}finally{setLoading(false);}}
 useEffect(()=>{void load();},[since,until]);const total=rows.reduce((a,r)=>({spend:a.spend+r.spend,leads:a.leads+r.leads,conversations:a.conversations+r.conversations,revenue:a.revenue+r.revenue}),{spend:0,leads:0,conversations:0,revenue:0});
 return <div className="space-y-4"><section className="page-heading"><div><p className="section-kicker">Administração</p><h1>Visão geral da agência</h1><p>Totais da carteira apenas como referência e, abaixo, cada empresa isolada em sua própria linha.</p></div><button className="secondary-button" onClick={()=>{void load();}} disabled={loading}><RefreshCw size={14} className={loading?'animate-spin':''}/>Atualizar</button></section><section className="filter-panel"><div className="grid gap-2 sm:grid-cols-2 max-w-xl"><label className="field-label"><span><CalendarRange size={12}/> Data inicial</span><input className="field-control" type="date" value={since} onChange={e=>setSince(e.target.value)}/></label><label className="field-label"><span><CalendarRange size={12}/> Data final</span><input className="field-control" type="date" value={until} onChange={e=>setUntil(e.target.value)}/></label></div></section>{error&&<div className="message-warning">{error}</div>}<section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div className="corporate-card p-4"><WalletCards size={15} className="text-[#176846]"/><p className="section-kicker mt-2">Investimento da carteira</p><strong className="mt-1 block text-[20px]">{money(total.spend)}</strong></div><div className="corporate-card p-4"><TrendingUp size={15} className="text-[#176846]"/><p className="section-kicker mt-2">Leads</p><strong className="mt-1 block text-[20px]">{integer(total.leads)}</strong></div><div className="corporate-card p-4"><Building2 size={15} className="text-[#176846]"/><p className="section-kicker mt-2">Empresas</p><strong className="mt-1 block text-[20px]">{rows.length}</strong></div><div className="corporate-card p-4"><TrendingUp size={15} className="text-[#176846]"/><p className="section-kicker mt-2">Receita atribuída</p><strong className="mt-1 block text-[20px]">{money(total.revenue)}</strong></div></section><section className="corporate-card overflow-hidden"><div className="table-scroll"><table className="corporate-table"><thead><tr><th>Empresa</th><th>BMs</th><th>Contas</th><th>Investimento</th><th>Leads</th><th>CPL</th><th>Conversas</th><th>Custo conv.</th><th>CTR</th><th>CPC</th><th>CPM</th><th>Compras</th><th>CPA</th><th>ROAS</th></tr></thead><tbody>{rows.sort((a,b)=>b.spend-a.spend).map(r=><tr key={r.clientId}><td><strong>{r.name}</strong>{r.error&&<small className="text-amber-600">{r.error}</small>}</td><td>{r.bmCount}</td><td>{r.accountCount}</td><td>{money(r.spend)}</td><td>{integer(r.leads)}</td><td>{money(r.costPerLead)}</td><td>{integer(r.conversations)}</td><td>{money(r.costPerConversation)}</td><td>{dec(r.ctr)}%</td><td>{money(r.cpc)}</td><td>{money(r.cpm)}</td><td>{integer(r.purchases)}</td><td>{money(r.costPerPurchase)}</td><td>{dec(r.roas)}x</td></tr>)}</tbody></table></div></section></div>}
