import { useEffect, useState } from 'react';
import { AlertTriangle, Bell, Check, RefreshCw, ShieldAlert } from 'lucide-react';
import { api } from '../api';
import { useAuth, useScope } from '../store';

type AlertRow={id:string;type:string;severity:string;title:string;message:string;isRead:boolean;createdAt:string;businessId?:string|null;clientId?:string|null};
export default function Alerts(){
  const user=useAuth(s=>s.user);const scope=useScope();const canEvaluate=['SUPER_ADMIN','AGENCY_ADMIN','MANAGER'].includes(user?.role||'');
  const[rows,setRows]=useState<AlertRow[]>([]);const[loading,setLoading]=useState(false);const[evaluating,setEvaluating]=useState(false);const[unreadOnly,setUnreadOnly]=useState(false);const[error,setError]=useState('');
  async function load(){setLoading(true);setError('');try{const r=await api.get('/workspace/alerts',{params:{...(scope.clientId?{clientId:scope.clientId}:{}),...(scope.businessId?{businessId:scope.businessId}:{}),...(unreadOnly?{unread:true}:{})}});setRows(Array.isArray(r.data?.data)?r.data.data:[]);}catch(e:any){setError(e?.response?.data?.error?.message||'Não foi possível carregar os alertas.');}finally{setLoading(false);}}
  useEffect(()=>{void load();},[scope.clientId,scope.businessId,unreadOnly]);
  async function evaluate(){if(!scope.clientId)return;setEvaluating(true);try{await api.post('/workspace/alerts/evaluate',{clientId:scope.clientId,...(scope.businessId?{businessId:scope.businessId}:{})});await load();}catch(e:any){setError(e?.response?.data?.error?.message||'Não foi possível avaliar o desempenho.');}finally{setEvaluating(false);}}
  async function read(id:string){try{await api.patch(`/workspace/alerts/${id}/read`);await load();window.dispatchEvent(new Event('gestao-ads:alerts-refresh'));}catch{setError('Não foi possível marcar o alerta como lido.');}}
  const severity=(s:string)=>s==='critical'?'border-red-200 bg-red-50 text-red-700':s==='warning'?'border-amber-200 bg-amber-50 text-amber-700':'border-slate-200 bg-slate-50 text-slate-600';
  return <div className="space-y-4"><section className="page-heading"><div><p className="section-kicker">Monitoramento</p><h1>Alertas</h1><p>Problemas e oportunidades separados por empresa e BM: gasto sem lead, CTR baixo, frequência alta, ROAS e integração.</p></div><div className="flex gap-2">{canEvaluate&&<button className="primary-button" onClick={()=>{void evaluate();}} disabled={!scope.clientId||evaluating}><ShieldAlert size={14}/>{evaluating?'Analisando':'Analisar agora'}</button>}<button className="secondary-button" onClick={()=>{void load();}} disabled={loading}><RefreshCw size={14} className={loading?'animate-spin':''}/></button></div></section>{error&&<div className="message-warning">{error}</div>}<section className="filter-panel"><label className="flex items-center gap-2 text-[11px] font-medium text-slate-600"><input type="checkbox" checked={unreadOnly} onChange={e=>setUnreadOnly(e.target.checked)}/> Mostrar somente não lidos <span className="status-chip status-neutral">{rows.filter(r=>!r.isRead).length} não lido(s)</span></label></section><div className="space-y-2">{rows.map(row=><article key={row.id} className={`rounded-[8px] border p-4 ${row.isRead?'border-[#e1e6e3] bg-white':severity(row.severity)}`}><div className="flex gap-3"><span className="mt-0.5 shrink-0">{row.severity==='critical'||row.severity==='warning'?<AlertTriangle size={17}/>:<Bell size={17}/>}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-start justify-between gap-2"><div><h2 className="text-[12px] font-semibold">{row.title}</h2><p className="mt-1 text-[11px] leading-5 opacity-90">{row.message}</p></div><span className="text-[9px] opacity-70">{new Date(row.createdAt).toLocaleString('pt-BR')}</span></div><div className="mt-3 flex items-center gap-2"><span className="status-chip status-neutral">{row.type}</span>{!row.isRead&&<button className="text-button" onClick={()=>{void read(row.id);}}><Check size={12}/> Marcar como lido</button>}</div></div></div></article>)}{!rows.length&&!loading&&<div className="corporate-card empty-state"><Bell size={20}/><span>Nenhum alerta neste escopo.</span></div>}</div></div>;
}
