import { useEffect, useState } from 'react';
import { FileClock, RefreshCw, ShieldCheck } from 'lucide-react';
import { api } from '../api';
import { useScope } from '../store';

type Log={id:string;userId?:string|null;businessId?:string|null;action:string;entity?:string|null;entityId?:string|null;metadataJson?:any;ip?:string|null;userAgent?:string|null;createdAt:string};
export default function Audit(){const scope=useScope();const[rows,setRows]=useState<Log[]>([]);const[loading,setLoading]=useState(false);const[error,setError]=useState('');
 async function load(){setLoading(true);try{const r=await api.get('/workspace/audit',{params:{...(scope.businessId?{businessId:scope.businessId}:{}),take:200}});setRows(Array.isArray(r.data?.data)?r.data.data:[]);}catch(e:any){setError(e?.response?.data?.error?.message||'Não foi possível carregar a auditoria.');}finally{setLoading(false);}}
 useEffect(()=>{void load();},[scope.businessId]);
 return <div className="space-y-4"><section className="page-heading"><div><p className="section-kicker">Governança</p><h1>Auditoria</h1><p>Registro das ações administrativas, conexões, contas, campanhas e acessos.</p></div><button className="secondary-button" onClick={()=>{void load();}} disabled={loading}><RefreshCw size={14} className={loading?'animate-spin':''}/>Atualizar</button></section>{error&&<div className="message-warning">{error}</div>}<section className="corporate-card overflow-hidden"><div className="table-scroll"><table className="corporate-table"><thead><tr><th>Data</th><th>Ação</th><th>Entidade</th><th>BM</th><th>Usuário</th><th>Detalhes</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td>{new Date(row.createdAt).toLocaleString('pt-BR')}</td><td><span className="status-chip status-neutral"><ShieldCheck size={11}/>{row.action}</span></td><td>{row.entity||'—'}<small>{row.entityId||''}</small></td><td>{row.businessId||'—'}</td><td>{row.userId||'Sistema'}</td><td className="max-w-[420px] whitespace-normal"><code className="text-[9px] text-slate-500">{row.metadataJson?JSON.stringify(row.metadataJson).slice(0,500):'—'}</code></td></tr>)}{!rows.length&&!loading&&<tr><td colSpan={6}><div className="empty-state"><FileClock size={20}/><span>Nenhum evento registrado neste filtro.</span></div></td></tr>}</tbody></table></div></section></div>}
