import { useEffect, useMemo, useState } from 'react';
import { BarChart3, CheckCircle2, ExternalLink, Link2, RefreshCw, Unplug } from 'lucide-react';
import { api } from '../api';
import { useAuth, useScope } from '../store';

type Connection={id:string;clientId:string;propertyId?:string|null;propertyName?:string|null;status:string;lastSyncAt?:string|null;lastError?:string|null};
type Property={propertyId:string;propertyName:string;accountName:string;accountId:string};
type Report={client:{id:string;name:string};property:{id:string;name?:string|null};period:{since:string;until:string};summary:{sessions:number;totalUsers:number;newUsers:number;engagedSessions:number;engagementRate:number;keyEvents:number;totalRevenue:number};daily:Array<{value:string;sessions:number;keyEvents:number;totalRevenue:number}>;channels:Array<{value:string;sessions:number;keyEvents:number;totalRevenue:number}>;googleAds:{available:boolean;warning?:string|null;totals:any;campaigns:any[]};updatedAt:string};

const iso=(date:Date)=>date.toISOString().slice(0,10);
function periodDays(days:number){const until=new Date();const since=new Date();since.setDate(until.getDate()-Math.max(0,days-1));return{since:iso(since),until:iso(until)};}
const money=(value:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(value||0));
const number=(value:number)=>new Intl.NumberFormat('pt-BR',{maximumFractionDigits:0}).format(Number(value||0));
const decimal=(value:number,digits=2)=>new Intl.NumberFormat('pt-BR',{minimumFractionDigits:digits,maximumFractionDigits:digits}).format(Number(value||0));

export default function GoogleAnalytics(){
 const user=useAuth(s=>s.user);const scope=useScope();const canAdmin=['SUPER_ADMIN','AGENCY_ADMIN'].includes(user?.role||'');
 const initial=periodDays(30);const[since,setSince]=useState(initial.since);const[until,setUntil]=useState(initial.until);const[configured,setConfigured]=useState(true);const[connection,setConnection]=useState<Connection|null>(null);const[properties,setProperties]=useState<Property[]>([]);const[propertyId,setPropertyId]=useState('');const[report,setReport]=useState<Report|null>(null);const[loading,setLoading]=useState(false);const[action,setAction]=useState('');const[error,setError]=useState('');
 const clientId=scope.clientId||((user?.role==='CLIENT'||user?.role==='MANAGER')?user?.clientId||'':'');
 const clientName=useMemo(()=>scope.clients.find(c=>c.id===clientId)?.name||report?.client?.name||'Empresa selecionada',[scope.clients,clientId,report]);

 async function loadStatus(){if(!clientId){setConnection(null);setReport(null);return;}try{const r=await api.get('/google-analytics/status',{params:{clientId}});setConfigured(Boolean(r.data?.data?.configured));const rows=Array.isArray(r.data?.data?.rows)?r.data.data.rows:[];const current=rows.find((row:Connection)=>row.clientId===clientId)||null;setConnection(current);setPropertyId(current?.propertyId||'');}catch(e:any){setError(e?.response?.data?.error?.message||'Não foi possível carregar a conexão do Google Analytics.');}}
 async function loadProperties(){if(!canAdmin||!clientId)return;try{const r=await api.get('/google-analytics/properties',{params:{clientId}});setProperties(Array.isArray(r.data?.data)?r.data.data:[]);}catch(e:any){setProperties([]);if(e?.response?.status!==409)setError(e?.response?.data?.error?.message||'Não foi possível listar as propriedades GA4.');}}
 async function loadReport(){if(!clientId||!connection||connection.status!=='active'||!connection.propertyId)return;setLoading(true);setError('');try{const r=await api.get('/google-analytics/report',{params:{clientId,since,until}});setReport(r.data?.data||null);await loadStatus();}catch(e:any){setReport(null);setError(e?.response?.data?.error?.message||'Não foi possível consultar os resultados do Google Analytics.');}finally{setLoading(false);}}
 useEffect(()=>{setReport(null);setProperties([]);void loadStatus();},[clientId]);
 useEffect(()=>{if(connection?.status==='active'&&connection.propertyId)void loadReport();},[connection?.id,connection?.propertyId,clientId]);

 async function connect(){if(!clientId)return;setAction('connect');setError('');const popup=window.open('about:blank','gestao-ads-google-analytics-oauth','width=760,height=860');try{const r=await api.get('/google-analytics/oauth/start',{params:{clientId}});const url=r.data?.data?.authUrl;if(!url)throw new Error('URL OAuth ausente');if(popup)popup.location.href=url;else window.location.assign(url);const timer=window.setInterval(async()=>{if(popup?.closed){clearInterval(timer);setAction('');await loadStatus();await loadProperties();}},1000);}catch(e:any){popup?.close();setAction('');setError(e?.response?.data?.error?.message||'Não foi possível iniciar a conexão com o Google Analytics.');}}
 async function saveProperty(){if(!clientId||!propertyId)return;setAction('property');setError('');try{await api.patch('/google-analytics/property',{clientId,propertyId});await loadStatus();setReport(null);}catch(e:any){setError(e?.response?.data?.error?.message||'Não foi possível vincular a propriedade GA4.');}finally{setAction('');}}
 async function disconnect(){if(!clientId||!window.confirm('Desconectar o Google Analytics desta empresa? A propriedade selecionada e a auditoria serão preservadas.'))return;setAction('disconnect');try{await api.post('/google-analytics/disconnect',{clientId});setReport(null);setProperties([]);await loadStatus();}catch(e:any){setError(e?.response?.data?.error?.message||'Não foi possível desconectar o Google Analytics.');}finally{setAction('');}}
 function applyPeriod(days:number){const p=periodDays(days);setSince(p.since);setUntil(p.until);}

 const ads=report?.googleAds;const adsTotals=ads?.totals||{};
 return <div className="space-y-4">
  <section className="page-heading"><div><p className="section-kicker">Mensuração</p><h1>Google Analytics & Google Ads</h1><p>Acompanhe GA4 e, quando o Google Ads estiver vinculado à propriedade, visualize investimento, cliques, impressões, eventos principais e retorno no mesmo escopo da empresa.</p></div><button className="secondary-button" disabled={loading||!clientId} onClick={()=>{void loadReport();}}><RefreshCw size={14} className={loading?'animate-spin':''}/>Atualizar dados</button></section>
  {!clientId&&<div className="message-warning">Selecione uma empresa no filtro superior para consultar o Google Analytics.</div>}
  {error&&<div className="message-warning">{error}</div>}
  {clientId&&<section className="corporate-card p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="panel-title">{clientName}</h2><p className="panel-subtitle">Integração individual por empresa · dados reais da propriedade GA4 selecionada.</p></div><span className={`status-chip ${connection?.status==='active'?'status-success':'status-neutral'}`}>{connection?.status==='active'?<CheckCircle2 size={12}/>:<Unplug size={12}/>} {connection?.status==='active'?'Google conectado':'Google desconectado'}</span></div>
   {!configured&&canAdmin&&<div className="message-warning mt-3">O módulo está instalado, mas o OAuth do Google precisa das variáveis GOOGLE_ANALYTICS_CLIENT_ID e GOOGLE_ANALYTICS_CLIENT_SECRET no EasyPanel.</div>}
   <div className="mt-4 grid gap-3 lg:grid-cols-[1fr_1fr_auto]">
    {canAdmin&&<><div><label className="field-label">Propriedade GA4</label><select className="field-control w-full" value={propertyId} onFocus={()=>{if(connection?.status==='active'&&!properties.length)void loadProperties();}} onChange={e=>setPropertyId(e.target.value)} disabled={connection?.status!=='active'}><option value="">Selecione a propriedade</option>{properties.map(p=><option key={p.propertyId} value={p.propertyId}>{p.accountName} · {p.propertyName} ({p.propertyId})</option>)}</select></div><div className="flex items-end"><button className="secondary-button" disabled={!propertyId||action==='property'||propertyId===connection?.propertyId} onClick={()=>{void saveProperty();}}>Salvar propriedade</button></div></>}
    <div className="flex items-end gap-2">{canAdmin&&<button className="primary-button" disabled={!configured||action==='connect'} onClick={()=>{void connect();}}><Link2 size={13}/>{connection?.status==='active'?'Reconectar Google':'Conectar Google'}</button>}{canAdmin&&connection?.status==='active'&&<button className="secondary-button text-red-600" disabled={action==='disconnect'} onClick={()=>{void disconnect();}}><Unplug size={13}/>Desconectar</button>}</div>
   </div>
   {connection?.propertyId&&<div className="mt-3 rounded-[7px] bg-[#f5f7f5] p-3 text-[10px] text-slate-600"><strong>{connection.propertyName||'Propriedade GA4'}</strong> · ID {connection.propertyId}{connection.lastSyncAt&&<> · última consulta {new Date(connection.lastSyncAt).toLocaleString('pt-BR')}</>}{connection.lastError&&<p className="mt-1 text-amber-700">{connection.lastError}</p>}</div>}
  </section>}
  {clientId&&connection?.status==='active'&&connection.propertyId&&<section className="filter-panel"><div className="flex flex-wrap items-end gap-2"><div><label className="field-label">De</label><input className="field-control" type="date" value={since} onChange={e=>setSince(e.target.value)}/></div><div><label className="field-label">Até</label><input className="field-control" type="date" value={until} onChange={e=>setUntil(e.target.value)}/></div><div className="flex gap-1">{[7,30,90].map(days=><button key={days} className="secondary-button" onClick={()=>applyPeriod(days)}>{days} dias</button>)}</div><button className="primary-button" disabled={loading} onClick={()=>{void loadReport();}}><RefreshCw size={13} className={loading?'animate-spin':''}/>Aplicar período</button></div></section>}
  {report&&<>
   <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div className="mini-stat"><span>Sessões</span><strong>{number(report.summary.sessions)}</strong><small>GA4 no período</small></div><div className="mini-stat"><span>Usuários</span><strong>{number(report.summary.totalUsers)}</strong><small>{number(report.summary.newUsers)} novos</small></div><div className="mini-stat"><span>Engajamento</span><strong>{decimal(report.summary.engagementRate*100,1)}%</strong><small>{number(report.summary.engagedSessions)} sessões engajadas</small></div><div className="mini-stat"><span>Eventos principais</span><strong>{decimal(report.summary.keyEvents,0)}</strong><small>Receita {money(report.summary.totalRevenue)}</small></div></section>
   <section className="corporate-card p-4"><div className="flex items-start justify-between gap-3"><div><p className="section-kicker">Google Ads via GA4</p><h2 className="panel-title">Desempenho de mídia paga</h2><p className="panel-subtitle">Custos e campanhas aparecem quando a conta Google Ads está vinculada à propriedade GA4 e possui dados no período.</p></div><BarChart3 size={18} className="text-[#2563eb]"/></div>
    {!ads?.available&&<div className="message-warning mt-3">{ads?.warning}</div>}
    {ads?.available&&<><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-6"><div className="mini-stat"><span>Investimento</span><strong>{money(adsTotals.cost)}</strong><small>Google Ads</small></div><div className="mini-stat"><span>Cliques</span><strong>{number(adsTotals.clicks)}</strong><small>CPC {money(adsTotals.cpc)}</small></div><div className="mini-stat"><span>Impressões</span><strong>{number(adsTotals.impressions)}</strong><small>mídia vinculada</small></div><div className="mini-stat"><span>Eventos principais</span><strong>{decimal(adsTotals.keyEvents||0,0)}</strong><small>CPA {money(adsTotals.costPerKeyEvent)}</small></div><div className="mini-stat"><span>Receita</span><strong>{money(adsTotals.revenue)}</strong><small>atribuída</small></div><div className="mini-stat"><span>ROAS</span><strong>{decimal(adsTotals.roas||0)}x</strong><small>receita / custo</small></div></div>
     <div className="table-scroll mt-4"><table className="corporate-table"><thead><tr><th>Campanha Google Ads</th><th>Sessões</th><th>Investimento</th><th>Cliques</th><th>Impressões</th><th>Eventos</th><th>CPA</th><th>Receita</th><th>ROAS</th></tr></thead><tbody>{ads.campaigns.map((row:any,index:number)=><tr key={`${row.customerId}-${row.name}-${index}`}><td><strong>{row.name}</strong><small>{row.customerId?`Conta ${row.customerId}`:'Google Ads'}</small></td><td>{number(row.sessions)}</td><td>{money(row.cost)}</td><td>{number(row.clicks)}</td><td>{number(row.impressions)}</td><td>{decimal(row.keyEvents,0)}</td><td>{money(row.costPerKeyEvent)}</td><td>{money(row.revenue)}</td><td>{decimal(row.roas)}x</td></tr>)}{!ads.campaigns.length&&<tr><td colSpan={9}>Nenhuma campanha Google Ads com dados atribuídos no período.</td></tr>}</tbody></table></div></>}
   </section>
   <section className="grid gap-3 lg:grid-cols-2"><article className="corporate-card p-4"><h2 className="panel-title">Canais de aquisição</h2><div className="table-scroll mt-3"><table className="corporate-table"><thead><tr><th>Canal</th><th>Sessões</th><th>Eventos</th><th>Receita</th></tr></thead><tbody>{report.channels.map((row,index)=><tr key={`${row.value}-${index}`}><td><strong>{row.value||'Não identificado'}</strong></td><td>{number(row.sessions)}</td><td>{decimal(row.keyEvents,0)}</td><td>{money(row.totalRevenue)}</td></tr>)}</tbody></table></div></article><article className="corporate-card p-4"><h2 className="panel-title">Evolução diária</h2><div className="table-scroll mt-3"><table className="corporate-table"><thead><tr><th>Data</th><th>Sessões</th><th>Eventos</th><th>Receita</th></tr></thead><tbody>{report.daily.slice(-31).map((row,index)=>{const d=row.value;const label=d&&d.length===8?`${d.slice(6,8)}/${d.slice(4,6)}/${d.slice(0,4)}`:d;return <tr key={`${d}-${index}`}><td>{label}</td><td>{number(row.sessions)}</td><td>{decimal(row.keyEvents,0)}</td><td>{money(row.totalRevenue)}</td></tr>})}</tbody></table></div></article></section>
   <section className="corporate-card p-4 text-[10px] text-slate-500"><span>Fonte: <strong>Google Analytics Data API (GA4)</strong></span> · <span>Atualizado em <strong>{new Date(report.updatedAt).toLocaleString('pt-BR')}</strong></span> · <a className="inline-flex items-center gap-1 font-semibold text-[#2563eb]" href="https://analytics.google.com/" target="_blank" rel="noreferrer">Abrir Google Analytics <ExternalLink size={10}/></a></section>
  </>}
  {clientId&&connection?.status==='active'&&!connection.propertyId&&<div className="empty-state corporate-card p-6"><BarChart3 size={20}/><span>{canAdmin?'Escolha e salve a propriedade GA4 desta empresa para começar.':'O administrador ainda não vinculou uma propriedade GA4 a esta empresa.'}</span></div>}
 </div>;
}
