import { useEffect, useMemo, useState } from 'react';
import {
  Activity, BarChart3, CheckCircle2, CircleDollarSign, Code2, Eye, MousePointerClick,
  RefreshCw, Save, ShieldCheck, ShoppingCart, Users, WalletCards,
} from 'lucide-react';
import { api } from '../api';
import { useAuth, useScope } from '../store';

type GaConfig={configured:boolean;propertyId?:string|null;serviceAccountEmail?:string|null;updatedAt?:string|null};
type GaReport={totals:{activeUsers:number;sessions:number;pageViews:number;keyEvents:number;transactions:number;revenue:number};series:Array<{date:string;activeUsers:number;sessions:number;pageViews:number;keyEvents:number;transactions:number;revenue:number}>};
type PixelItem={id:string;name:string;lastFiredTime?:string|null};
type PixelState={configured:boolean;selectedPixel?:{pixelId:string;pixelName:string;businessId:string}|null;pixels:PixelItem[];discoveryError?:string|null};
type FinanceAccount={id:string;accountId:string;name?:string|null;currency?:string|null;businessId?:string|null;businessName?:string|null;finance?:{amountSpent?:string|number|null;balance?:string|number|null;spendCap?:string|number|null;currency?:string|null;fundingSource?:string|null;fundingSourceDetails?:any;isPrepayAccount?:boolean|null;timezone?:string|null}|null;financialError?:string|null;transactionsAvailable:boolean;transactionsError?:string|null;transactions:Array<{id:string;date?:string|null;type?:string|null;status?:string|null;amount?:string|number|null;currency?:string|null;description?:string|null}>};

function isoDate(date:Date){return date.toISOString().slice(0,10);}
function defaultSince(){const d=new Date();d.setDate(d.getDate()-29);return isoDate(d);}
function displayDate(value?:string|null){if(!value)return '—';const text=String(value);if(/^\d{8}$/.test(text))return `${text.slice(6,8)}/${text.slice(4,6)}/${text.slice(0,4)}`;const d=new Date(text);return Number.isNaN(d.getTime())?text:d.toLocaleDateString('pt-BR');}
function money(value:number,currency='BRL'){try{return new Intl.NumberFormat('pt-BR',{style:'currency',currency}).format(value||0);}catch{return String(value||0);}}
function metaMoney(value:unknown,currency='BRL'){const n=Number(value);if(!Number.isFinite(n))return '—';let digits=2;try{digits=new Intl.NumberFormat('pt-BR',{style:'currency',currency}).resolvedOptions().maximumFractionDigits;}catch{}return money(n/Math.pow(10,digits),currency);}

export default function MarketingIntelligence(){
 const user=useAuth(s=>s.user);const scope=useScope();const canAdmin=['SUPER_ADMIN','AGENCY_ADMIN'].includes(user?.role||'');
 const[since,setSince]=useState(defaultSince());const[until,setUntil]=useState(isoDate(new Date()));const[loading,setLoading]=useState(false);const[saving,setSaving]=useState('');const[error,setError]=useState('');const[success,setSuccess]=useState('');
 const[gaConfig,setGaConfig]=useState<GaConfig|null>(null);const[gaProperty,setGaProperty]=useState('');const[gaJson,setGaJson]=useState('');const[gaReport,setGaReport]=useState<GaReport|null>(null);
 const[pixelState,setPixelState]=useState<PixelState|null>(null);const[pixelId,setPixelId]=useState('');const[pixelStats,setPixelStats]=useState<any[]>([]);
 const[finance,setFinance]=useState<FinanceAccount[]>([]);
 const business=scope.businesses.find(b=>b.clientId===scope.clientId&&b.metaBusinessId===scope.businessId);const client=scope.clients.find(c=>c.id===scope.clientId);

 async function loadConfig(){
  if(!scope.clientId)return;
  try{
   const r=await api.get('/workspace/google-analytics/config',{params:{clientId:scope.clientId}});const data=r.data?.data as GaConfig;setGaConfig(data);if(data?.propertyId)setGaProperty(data.propertyId);
  }catch(e:any){setError(e?.response?.data?.error?.message||'Não foi possível carregar a configuração do Google Analytics.');}
 }
 async function loadPixels(){
  if(!scope.clientId||!scope.businessId){setPixelState(null);setPixelStats([]);return;}
  try{
   const r=await api.get('/workspace/meta-pixels',{params:{clientId:scope.clientId,businessId:scope.businessId}});const data=r.data?.data as PixelState;setPixelState(data);setPixelId(data?.selectedPixel?.pixelId||'');
  }catch(e:any){setPixelState(null);setError(e?.response?.data?.error?.message||'Não foi possível consultar os Pixels da empresa.');}
 }
 async function loadData(){
  if(!scope.clientId)return;setLoading(true);setError('');setSuccess('');
  const jobs:Promise<any>[]=[];
  jobs.push(api.get('/workspace/finance',{params:{clientId:scope.clientId,...(scope.businessId?{businessId:scope.businessId}:{}),...(scope.adAccountId?{adAccountId:scope.adAccountId}:{}),since,until}}).then(r=>setFinance(Array.isArray(r.data?.data?.accounts)?r.data.data.accounts:[])).catch(e=>{setFinance([]);setError(e?.response?.data?.error?.message||'Não foi possível consultar o financeiro da Meta.');}));
  if(gaConfig?.configured)jobs.push(api.get('/workspace/google-analytics/report',{params:{clientId:scope.clientId,since,until}}).then(r=>setGaReport(r.data?.data||null)).catch(e=>{setGaReport(null);setError(e?.response?.data?.error?.message||'Não foi possível consultar o Google Analytics.');}));else setGaReport(null);
  if(scope.businessId&&pixelState?.configured)jobs.push(api.get('/workspace/meta-pixels/stats',{params:{clientId:scope.clientId,businessId:scope.businessId,since,until}}).then(r=>setPixelStats(Array.isArray(r.data?.data?.stats)?r.data.data.stats:[])).catch(e=>{setPixelStats([]);setError(e?.response?.data?.error?.message||'Não foi possível consultar as métricas do Pixel.');}));else setPixelStats([]);
  await Promise.all(jobs);setLoading(false);
 }
 useEffect(()=>{void loadConfig();},[scope.clientId]);
 useEffect(()=>{void loadPixels();},[scope.clientId,scope.businessId]);
 useEffect(()=>{if(gaConfig!==null&&(!scope.businessId||pixelState!==null))void loadData();},[scope.clientId,scope.businessId,scope.adAccountId,gaConfig?.configured,pixelState?.configured]);

 async function saveGa(e:React.FormEvent){e.preventDefault();if(!scope.clientId||!gaProperty.trim()||!gaJson.trim())return;setSaving('ga');setError('');setSuccess('');try{await api.put('/workspace/google-analytics/config',{clientId:scope.clientId,propertyId:gaProperty.trim(),serviceAccountJson:gaJson.trim()});setGaJson('');setSuccess('Google Analytics conectado à empresa.');await loadConfig();}catch(e:any){setError(e?.response?.data?.error?.message||'Não foi possível salvar o Google Analytics.');}finally{setSaving('');}}
 async function savePixel(){if(!scope.clientId||!scope.businessId||!pixelId)return;const pixel=pixelState?.pixels.find(p=>p.id===pixelId);if(!pixel)return;setSaving('pixel');setError('');setSuccess('');try{await api.put('/workspace/meta-pixels/config',{clientId:scope.clientId,businessId:scope.businessId,pixelId:pixel.id,pixelName:pixel.name});setSuccess('Pixel vinculado à empresa e à BM.');await loadPixels();}catch(e:any){setError(e?.response?.data?.error?.message||'Não foi possível vincular o Pixel.');}finally{setSaving('');}}

 const pixelEvents=useMemo(()=>pixelStats.reduce((total,row)=>total+Number(row?.count||row?.value||row?.events||0),0),[pixelStats]);
 const rechargeRows=useMemo(()=>finance.flatMap(account=>account.transactions.map(tx=>({...tx,accountName:account.name||account.accountId,accountCurrency:account.finance?.currency||account.currency||'BRL'}))),[finance]);

 return <div className="space-y-4">
  <section className="page-heading"><div><p className="section-kicker">Medição e atribuição</p><h1>Google Analytics, Pixel e Financeiro</h1><p>Visão consolidada por empresa e Business Manager, sempre respeitando o escopo do usuário.</p></div><button className="primary-button" onClick={()=>{void loadData();}} disabled={loading||!scope.clientId}><RefreshCw size={14} className={loading?'animate-spin':''}/>{loading?'Atualizando':'Atualizar dados'}</button></section>
  {error&&<div className="message-warning">{error}</div>}{success&&<div className="rounded-[8px] border border-emerald-200 bg-emerald-50 px-3 py-2 text-[11px] text-emerald-700">{success}</div>}
  <section className="filter-panel"><div className="grid gap-2 md:grid-cols-4"><label className="field-label">Empresa<input className="field-control" value={client?.name||'Selecione no topo'} readOnly/></label><label className="field-label">Business Manager<input className="field-control" value={business?.name||'Selecione no topo'} readOnly/></label><label className="field-label">Período inicial<input className="field-control" type="date" value={since} onChange={e=>setSince(e.target.value)}/></label><label className="field-label">Período final<input className="field-control" type="date" value={until} onChange={e=>setUntil(e.target.value)}/></label></div><div className="mt-3 flex justify-end"><button className="secondary-button" onClick={()=>{void loadData();}} disabled={loading||!scope.clientId}><RefreshCw size={13}/>Aplicar período</button></div></section>

  <section className="corporate-card p-4"><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2"><BarChart3 size={16} className="text-[#2563eb]"/><h2 className="panel-title">Google Analytics 4</h2></div><p className="panel-subtitle">Audiência, sessões, visualizações, eventos-chave, transações e receita do cliente.</p></div><span className={`status-chip ${gaConfig?.configured?'status-success':'status-neutral'}`}>{gaConfig?.configured?<CheckCircle2 size={12}/>:<Activity size={12}/>} {gaConfig?.configured?'Conectado':'Não configurado'}</span></div>
   {gaConfig?.configured&&<div className="mt-3 text-[10px] text-slate-500">Property <b>{gaConfig.propertyId}</b> · Conta de serviço <b>{gaConfig.serviceAccountEmail}</b></div>}
   {gaReport?<div className="mt-4 grid gap-2 sm:grid-cols-2 xl:grid-cols-6"><div className="mini-stat"><span>Usuários ativos</span><strong>{gaReport.totals.activeUsers.toLocaleString('pt-BR')}</strong><small>GA4</small></div><div className="mini-stat"><span>Sessões</span><strong>{gaReport.totals.sessions.toLocaleString('pt-BR')}</strong><small>tráfego</small></div><div className="mini-stat"><span>Visualizações</span><strong>{gaReport.totals.pageViews.toLocaleString('pt-BR')}</strong><small>páginas/telas</small></div><div className="mini-stat"><span>Eventos-chave</span><strong>{gaReport.totals.keyEvents.toLocaleString('pt-BR')}</strong><small>conversões GA4</small></div><div className="mini-stat"><span>Transações</span><strong>{gaReport.totals.transactions.toLocaleString('pt-BR')}</strong><small>e-commerce</small></div><div className="mini-stat"><span>Receita</span><strong>{money(gaReport.totals.revenue)}</strong><small>GA4</small></div></div>:<div className="mt-4 rounded-[7px] bg-[#f5f7f5] p-3 text-[10px] text-slate-500">{gaConfig?.configured?'Aplique o período para carregar as métricas do GA4.':'O administrador precisa cadastrar a propriedade GA4 deste cliente.'}</div>}
   {canAdmin&&<form onSubmit={saveGa} className="mt-4 grid gap-2 border-t border-[#e1e6e3] pt-3 md:grid-cols-[220px_1fr_auto]"><label className="field-label">GA4 Property ID<input className="field-control" value={gaProperty} onChange={e=>setGaProperty(e.target.value)} placeholder="Ex.: 123456789"/></label><label className="field-label">JSON da conta de serviço<textarea className="field-control min-h-[72px] resize-y py-2" value={gaJson} onChange={e=>setGaJson(e.target.value)} placeholder="Cole o JSON da Service Account do Google Cloud. A chave privada será criptografada no backend."/></label><div className="flex items-end"><button className="primary-button mb-[1px]" disabled={saving==='ga'||!scope.clientId||!gaProperty.trim()||!gaJson.trim()}><Save size={13}/>{saving==='ga'?'Salvando':'Salvar conexão'}</button></div></form>}
  </section>

  <section className="corporate-card p-4"><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2"><Code2 size={16} className="text-[#2563eb]"/><h2 className="panel-title">Meta Pixel</h2></div><p className="panel-subtitle">Pixel vinculado à empresa/BM para acompanhar eventos reais enviados à Meta.</p></div><span className={`status-chip ${pixelState?.configured?'status-success':'status-neutral'}`}>{pixelState?.configured?<ShieldCheck size={12}/>:<Activity size={12}/>} {pixelState?.configured?'Vinculado':'Não vinculado'}</span></div>
   {pixelState?.selectedPixel&&<div className="mt-3 rounded-[7px] border border-[#e1e6e3] p-3 text-[10px]"><b>{pixelState.selectedPixel.pixelName}</b><span className="ml-2 text-slate-400">ID {pixelState.selectedPixel.pixelId}</span></div>}
   <div className="mt-3 grid gap-2 sm:grid-cols-3"><div className="mini-stat"><span>Eventos no período</span><strong>{pixelEvents.toLocaleString('pt-BR')}</strong><small>retornados pela Meta</small></div><div className="mini-stat"><span>Pixels disponíveis</span><strong>{pixelState?.pixels?.length||0}</strong><small>na BM selecionada</small></div><div className="mini-stat"><span>Último disparo</span><strong>{displayDate(pixelState?.pixels?.find(p=>p.id===(pixelState.selectedPixel?.pixelId||pixelId))?.lastFiredTime)}</strong><small>Meta</small></div></div>
   {pixelState?.discoveryError&&<div className="message-warning mt-3">{pixelState.discoveryError}</div>}
   {canAdmin&&<div className="mt-4 flex flex-col gap-2 border-t border-[#e1e6e3] pt-3 sm:flex-row sm:items-end"><label className="field-label flex-1">Pixel da BM<select className="field-control" value={pixelId} onChange={e=>setPixelId(e.target.value)} disabled={!scope.businessId}><option value="">Selecione</option>{pixelState?.pixels?.map(p=><option key={p.id} value={p.id}>{p.name} · {p.id}</option>)}</select></label><button className="primary-button" disabled={saving==='pixel'||!pixelId||!scope.businessId} onClick={()=>{void savePixel();}}><Save size={13}/>{saving==='pixel'?'Salvando':'Vincular Pixel'}</button></div>}
  </section>

  <section className="corporate-card overflow-hidden"><div className="flex flex-wrap items-start justify-between gap-3 border-b border-[#e1e6e3] p-4"><div><div className="flex items-center gap-2"><CircleDollarSign size={16} className="text-[#2563eb]"/><h2 className="panel-title">Financeiro e histórico de recargas Meta</h2></div><p className="panel-subtitle">Saldo, gasto, limite e transações por conta de anúncio, empresa e BM.</p></div><span className="status-chip status-neutral"><WalletCards size={12}/>{finance.length} conta(s)</span></div>
   <div className="grid gap-3 p-4 lg:grid-cols-2">{finance.map(account=>{const currency=account.finance?.currency||account.currency||'BRL';return <article key={account.id} className="rounded-[8px] border border-[#e1e6e3] p-3"><div className="flex items-start justify-between gap-2"><div><strong className="text-[11px]">{account.name||account.accountId}</strong><small className="block text-[9px] text-slate-400">Conta {account.accountId} · {account.businessName||'BM'}</small></div><span className={`status-chip ${account.finance?'status-success':'status-warning'}`}>{account.finance?'Financeiro ativo':'Limitado'}</span></div><div className="mt-3 grid grid-cols-3 gap-2"><div className="mini-stat"><span>Saldo</span><strong>{metaMoney(account.finance?.balance,currency)}</strong><small>{currency}</small></div><div className="mini-stat"><span>Gasto acumulado</span><strong>{metaMoney(account.finance?.amountSpent,currency)}</strong><small>Meta</small></div><div className="mini-stat"><span>Limite</span><strong>{metaMoney(account.finance?.spendCap,currency)}</strong><small>spend cap</small></div></div>{account.financialError&&<p className="mt-2 text-[9px] text-amber-700">{account.financialError}</p>}<div className="mt-3 border-t border-[#edf0ee] pt-2 text-[9px] text-slate-500"><b>{account.transactions.length}</b> transação(ões) no período. {!account.transactionsAvailable&&<span className="text-amber-700"> A Meta não liberou o histórico para este token: {account.transactionsError}</span>}</div></article>})}{!finance.length&&!loading&&<div className="empty-state col-span-full"><WalletCards size={20}/><span>Nenhuma conta autorizada encontrada neste escopo.</span></div>}</div>
   <div className="table-scroll border-t border-[#e1e6e3]"><table className="corporate-table"><thead><tr><th>Data</th><th>Conta</th><th>Tipo</th><th>Status</th><th>Valor</th><th>Descrição</th></tr></thead><tbody>{rechargeRows.map((row,index)=><tr key={`${row.id||'tx'}-${index}`}><td>{displayDate(row.date)}</td><td>{row.accountName}</td><td>{row.type||'Transação'}</td><td>{row.status||'—'}</td><td>{metaMoney(row.amount,row.currency||row.accountCurrency)}</td><td>{row.description||'—'}</td></tr>)}{!rechargeRows.length&&<tr><td colSpan={6}><div className="empty-state"><CircleDollarSign size={18}/><span>Nenhuma transação retornada pela Meta para o período selecionado.</span></div></td></tr>}</tbody></table></div>
  </section>

  <section className="grid gap-3 md:grid-cols-4"><div className="corporate-card p-3"><Users size={15}/><p className="mt-2 text-[10px] font-semibold">Audiência</p><small className="text-[9px] text-slate-400">GA4 por empresa</small></div><div className="corporate-card p-3"><MousePointerClick size={15}/><p className="mt-2 text-[10px] font-semibold">Eventos</p><small className="text-[9px] text-slate-400">Pixel por BM</small></div><div className="corporate-card p-3"><Eye size={15}/><p className="mt-2 text-[10px] font-semibold">Visibilidade</p><small className="text-[9px] text-slate-400">Cliente acompanha seu escopo</small></div><div className="corporate-card p-3"><ShoppingCart size={15}/><p className="mt-2 text-[10px] font-semibold">Resultado</p><small className="text-[9px] text-slate-400">Marketing e receita no mesmo painel</small></div></section>
 </div>;
}
