import { Bell, Database, Link2, MessageSquareText, RefreshCw, Settings2, ShieldCheck, Users } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { useAuth, useScope } from '../store';

export default function Settings(){
 const navigate=useNavigate();const user=useAuth(s=>s.user);const scope=useScope();const admin=['SUPER_ADMIN','AGENCY_ADMIN'].includes(user?.role||'');
 const cards=[
  ['Integração Meta','Conexões, tokens, permissões e saúde das BMs.','/integracoes',Link2],
  ['Usuários e acessos','Vínculos por empresa, BM e perfil.','/usuarios',Users],
  ['Alertas','Regras e ocorrências para tomada de decisão.','/alertas',Bell],
  ['Atendimento','Chat interno, chamados, arquivos e áudio.','/atendimento',MessageSquareText],
  ['Business Managers','Estrutura e sincronização independente.','/business-managers',Database],
 ];
 return <div className="space-y-4"><section className="page-heading"><div><p className="section-kicker">Sistema</p><h1>Configurações</h1><p>Configurações operacionais ficam agrupadas aqui. O usuário comum não vê informações técnicas espalhadas no dashboard.</p></div></section><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{cards.filter(([title])=>admin||!['Usuários e acessos'].includes(String(title))).map(([title,description,path,Icon]:any)=><button key={path} className="corporate-card p-4 text-left transition hover:border-[#b9c9c0] hover:bg-[#fbfcfb]" onClick={()=>navigate(path)}><span className="metric-icon"><Icon size={15}/></span><h2 className="mt-3 text-[12px] font-semibold">{title}</h2><p className="mt-1 text-[10px] leading-4 text-slate-500">{description}</p></button>)}</section><section className="corporate-card p-4"><div className="flex gap-3"><ShieldCheck size={17} className="mt-0.5 text-[#176846]"/><div><h2 className="panel-title">Escopo atual</h2><p className="panel-subtitle">As páginas operacionais herdam este escopo automaticamente.</p><div className="mt-3 grid gap-2 sm:grid-cols-3"><div className="mini-stat"><span>Empresa</span><strong>{scope.clients.find(c=>c.id===scope.clientId)?.name||'—'}</strong><small>ID interno</small></div><div className="mini-stat"><span>Business Manager</span><strong>{scope.businesses.find(b=>b.metaBusinessId===scope.businessId&&b.clientId===scope.clientId)?.name||'Todas/—'}</strong><small>{scope.businessId||'sem filtro'}</small></div><div className="mini-stat"><span>Conta Meta</span><strong>{scope.accounts.find(a=>a.id===scope.adAccountId)?.name||'Todas'}</strong><small>{scope.accounts.find(a=>a.id===scope.adAccountId)?.accountId||'sem filtro'}</small></div></div></div></div></section><section className="corporate-card p-4"><div className="flex items-center gap-2"><RefreshCw size={14} className="text-[#176846]"/><h2 className="panel-title">Atualização de dados</h2></div><p className="mt-2 text-[10px] leading-5 text-slate-500">Sincronização automática configurada a cada 5 minutos, isolada por empresa e BM. Uma falha em uma BM não interrompe as demais. O histórico importado permanece preservado em desconexões.</p></section></div>;
}
